services:
    sergei_k_avangard.admin.client:
        class: SergeiK\AvangardBundle\Admin\ClientAdmin
        arguments: [~, SergeiK\AvangardBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Client}

    sergei_k_avangard.admin.car:
        class: SergeiK\AvangardBundle\Admin\CarAdmin
        arguments: [~, SergeiK\AvangardBundle\Entity\Car, SergeiKAvangardBundle:CarAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Car}

    sergei_k_avangard.admin.company:
        class: SergeiK\AvangardBundle\Admin\CompanyAdmin
        arguments: [~, SergeiK\AvangardBundle\Entity\Company, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Company}

    sergei_k_avangard.admin.commision_contract:
        class: SergeiK\AvangardBundle\Admin\CommisionContractAdmin
        arguments: [~, SergeiK\AvangardBundle\Entity\CommisionContract, SergeiKAvangardBundle:CommisionContractAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CommisionContract}

    sergei_k_avangard.admin.sale_contract:
        class: SergeiK\AvangardBundle\Admin\SaleContractAdmin
        arguments: [~, SergeiK\AvangardBundle\Entity\SaleContract, SergeiKAvangardBundle:SaleContractAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: SaleContract}

    sergei_k_avangard.admin.deposit_contract:
        class: SergeiK\AvangardBundle\Admin\DepositContractAdmin
        arguments: [~, SergeiK\AvangardBundle\Entity\DepositContract, SergeiKAvangardBundle:DepositContractAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: DepositContract}

    sonata.block.service.fub:
        class: SergeiK\AvangardBundle\Block\FUBBlockService
        arguments: [ "sonata.block.service.FUB", @templating ]
        tags:
            - { name: sonata.block }
